# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb

RSpec/NamedSubject:
  Enabled: false

# RSpec
RSpec:
  Enabled: true

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4
